LDLIBS=-lgc

gc-template: gc-template.o gc-list.o
gc-list-test: gc-list-test.o gc-list.o

gc-template.o: list.h gc-template.c
gc-list-test.o: list.h gc-list-test.c
gc-list.o: list.h gc-list.c

gc-bits.o: bits.h gc-bits.c
